# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keys_pairs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10keys_pairs.proto\")\n\x12\x45ncryptKeysRequest\x12\x13\n\x0bsystem_code\x18\x01 \x01(\t\"-\n\x13\x45ncryptKeysResponse\x12\x16\n\x0e\x65ncrypted_data\x18\x01 \x01(\t2J\n\x10KeysPairsService\x12\x36\n\tkeysPairs\x12\x13.EncryptKeysRequest\x1a\x14.EncryptKeysResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keys_pairs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENCRYPTKEYSREQUEST']._serialized_start=20
  _globals['_ENCRYPTKEYSREQUEST']._serialized_end=61
  _globals['_ENCRYPTKEYSRESPONSE']._serialized_start=63
  _globals['_ENCRYPTKEYSRESPONSE']._serialized_end=108
  _globals['_KEYSPAIRSSERVICE']._serialized_start=110
  _globals['_KEYSPAIRSSERVICE']._serialized_end=184
# @@protoc_insertion_point(module_scope)
