site_name: Cephalopodus Gateway API
site_url: https://ogarcia-dev.github.io/Gateway/
site_dir: documentation/docs/es

theme:
  language: es
  name: material
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: amber

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

nav:
  - Inicio: 'es/index.md'
  - Versiones: 'es/release.md'