site_name: Cephalopodus API Gateway
site_url: https://ogarcia-dev.github.io/Gateway/
site_dir: documentation/docs/en

theme:
  language: en
  name: material
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: amber

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

nav:
  - Home: 'index.md'
  - Release Notes: 'release.md'

  - Getting Started:
    - Architecture: 'started/architecture/architecture.md'

    - Vault:
      - Vault: 'started/vault/vault.md'
      - Protobufs: 'started/vault/protobufs.md'

    - Gateway:
      - Gateway: 'started/gateway/gateway.md'
      - Http: 'started/gateway/http.md'
      - Websocket: 'started/gateway/websocket.md'
    
      - Authentication:
        - login: 'started/gateway/authentication/login.md'
        - register: 'started/gateway/authentication/register.md'
    
    - Administrator:
      - Administrator Started: 'started/administrator/administrator.md'
      - Administration:
        - Administration: 'started/administrator/administration/administration.md'
        - Systems: 'started/administrator/administration/systems.md'
        - Roles: 'started/administrator/administration/roles.md'
        - Groups: 'started/administrator/administration/groups.md'
        - Users: 'started/administrator/administration/users.md'
      
      - Services Discover:
        - Services Discover: 'started/administrator/service_discover/service_discover.md'
        - Microservices: 'started/administrator/service_discover/microservices.md'
        - Endpoints: 'started/administrator/service_discover/endpoints.md'

      - Parameters: 'started/administrator/parameter.md'
      - Menus: 'started/administrator/menu.md'

