name: Site Documentation Cephalopodus API Gateway

on:
  push:
    branches: ["master", "develop"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debugging - Before Build
        run: ls -R documentation/docs

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install required packages
        run: pip install -r documentation/requirements.txt --no-cache-dir

      - name: Setup caching
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}
          path: documentation/.cache

      - name: Build site
        run: cd documentation && mkdocs build --config-file mkdocs.yml --site-dir site

      - name: Debugging - After Build
        run: ls -R documentation/docs

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-site
          path: documentation/docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
