name: Site Documentation Cephalopodus API Gateway

on:
  push:
    branches:
      - master
      - develop

permissions:
  contenta: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

      run: pip install mkdocs mkdocs-material
      run: cd documentation && mkdocs gh-deploy --force