name: Site Documentation Cephalopodus API Gateway

on:
  push:
    branches:
      - master
      - main
      - develop
      - gh-pages

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: cd documentation/languages/en && mkdocs gh-deploy --force